[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "fusion-transcript-oncology-engine"
version = "2.0.0"
description = "FusionMind: RNA-Seq & NGS Oncogenic Gene Fusion Actionability Classifier"
readme = "README.md"
authors = [{ name = "Dr. Abu Suraih Sakhri", email = "abusuraih@example.com" }]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Medical Science Apps.",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
fusion-transcript-oncology-engine = "fusion_transcript_oncology_agent.cli:main"

[project.urls]
Homepage = "https://github.com/abusuraihsakhri/fusion-transcript-oncology-engine"
Repository = "https://github.com/abusuraihsakhri/fusion-transcript-oncology-engine.git"
